/*
 * Declare a mergeable PROGBITS data section named `eBuild.config' that contains
 * zero terminated strings only.
 *
 * When given as a section attribute to GCC, the following assembly code is
 * generated :
 * <asm>
 * .section	.eBuild.config,"MS",@progbits,1#,"a"
 * </asm>
 *
 * The trailing `#' sharp character is required here to comment the trailing
 * portion of assembly code generated by the `section' attribute which creates
 * an allocatable ELF section. Indeed, the simple C code below :
 * <c>
 * const char var[] __attribute__((section("eBuild.config"))
 * </c>
 * would generate the following assembly `.section' directive :
 * <asm>
 * .section	.eBuild.config,"a"
 * </asm>
 *
 * See section `.section name' of GNU as manual for more infos:
 * https://sourceware.org/binutils/docs/as/Section.html
 */
#define __EBUILD_CONFIG_SECTION \
	".eBuild.config,\"MS\",@progbits,1#"

#define EBUILD_CONFIG(_var) \
	const char _var[] __attribute__((section(__EBUILD_CONFIG_SECTION), \
	                                 used))

/*
 * Define the __ebuild_config character array with content located into a
 * `eBuild.config' ELF section with attributes set above.
 */
static EBUILD_CONFIG(__ebuild_config) =
	"CONFIG_CUTE_INTERN_ASSERT=y"
	"CONFIG_CUTE_UTEST=y";
